### ISSUE TITLE
How to specify the OpenAI API key ?

### ISSUE THREAD

**Issue by pligor** [ddupont808/GPT-4V-Act#10]
following the quick start guide when executing `npm start`, electron is loaded but then error like the one below appear.
Most likely the lack of the GPT-4 API Key is making it not work.

```
2024-03-24 21:26:20.512 Electron[3538:12247424] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
[3538:0324/212620.956073:ERROR:trust_store_mac.cc(414)] Error parsing certificate:
ERROR: Unexpected extensions (must be V3 certificate)
ERROR: Failed parsing TBSCertificate

[3538:0324/212620.957650:ERROR:trust_store_mac.cc(846)] Error parsing certificate:
ERROR: Unexpected extensions (must be V3 certificate)
ERROR: Failed parsing TBSCertificate

Acquired webviewId 2
(node:3538) UnhandledPromiseRejectionWarning: TargetCloseError: Waiting for selector `input[type="file"]` failed: Protocol error (Runtime.callFunctionOn): Target closed
    at CallbackRegistry.clear (/Users/gp/Desktop/ai-browser/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:139:36)
    at CdpCDPSession._onClosed (/Users/gp/Desktop/ai-browser/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/CDPSession.js:97:25)
    at Connection.onMessage (/Users/gp/Desktop/ai-browser/node_modules/puppeteer-core/lib/cjs/puppeteer/cdp/Connection.js:249:25)
    at WebSocket.<anonymous> (/Users/gp/Desktop/ai-browser/node_modules/puppeteer-core/lib/cjs/puppeteer/node/NodeWebSocketTransport.js:52:32)
    at callListener (/Users/gp/Desktop/ai-browser/node_modules/ws/lib/event-target.js:290:14)
    at WebSocket.onMessage (/Users/gp/Desktop/ai-browser/node_modules/ws/lib/event-target.js:209:9)
    at WebSocket.emit (node:events:514:28)
    at Receiver.receiverOnMessage (/Users/gp/Desktop/ai-browser/node_modules/ws/lib/websocket.js:1192:20)
    at Receiver.emit (node:events:514:28)
    at Receiver.dataMessage (/Users/gp/Desktop/ai-browser/node_modules/ws/lib/receiver.js:560:14)
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:3538) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
^C/Users/gp/Desktop/ai-browser/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGINT
```

**Comment by ddupont808** [comment]
added GPT-4 API key support in the latest push, you can now add it to your env variables (OPENAI_API_KEY)
