### ISSUE TITLE
UnhandledPromiseRejectionWarning

### ISSUE THREAD

**Issue by alxcnwy** [ddupont808/GPT-4V-Act#11]
Hi!

The app starts but when I type a command, there's no reply and get the following terminal output:

```
> ai-browser@1.0.0 start
> electron .

(node:58463) UnhandledPromiseRejectionWarning: Error: Could not find Chrome (ver. 118.0.5993.70). This can occur if either
 1. you did not perform an installation before running the script (e.g. `npm install`) or
 2. your cache path is incorrectly configured (which is: /Users/alexc/.cache/puppeteer).
For (2), check out our guide on configuring puppeteer at https://pptr.dev/guides/configuration.
    at ChromeLauncher.resolveExecutablePath (/Users/alexc/Documents/__HACKFS/gpt4v_act/ai-browser/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ProductLauncher.js:298:27)
    at ChromeLauncher.executablePath (/Users/alexc/Documents/__HACKFS/gpt4v_act/ai-browser/node_modules/puppeteer-core/lib/cjs/puppeteer/node/ChromeLauncher.js:196:25)
    at PuppeteerNode.executablePath (/Users/alexc/Documents/__HACKFS/gpt4v_act/ai-browser/node_modules/puppeteer-core/lib/cjs/puppeteer/node/PuppeteerNode.js:170:31)
    at OpenAIChatController.initialize (/Users/alexc/Documents/__HACKFS/gpt4v_act/ai-browser/chatgpt.js:21:29)
    at /Users/alexc/Documents/__HACKFS/gpt4v_act/ai-browser/main.js:301:20
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:58463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
Acquired webviewId 2
(node:58463) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'
(node:58463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:58463) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'
(node:58463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
Acquired webviewId 2
(node:58463) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'
(node:58463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:58463) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'
(node:58463) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

**Comment by alikonainofficial** [comment]
I'm getting the same issue:

```
2024-06-18 02:34:02.936 Electron[13235:349734] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
Acquired webviewId 2
(node:13235) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'
(Use `Electron --trace-warnings ...` to show where the warning was created)
(node:13235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:13235) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'
(node:13235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:13235) UnhandledPromiseRejectionWarning: Error: ENOENT: no such file or directory, open 'tmp/screenshot.png'
(node:13235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)

```

Nothing happens when I give any prompt.
However, when I click Auto Export, it starts going to random sites and behaving weirdly. Here's the logs when I click Auto Export and close the browser window after a while :

```
Acquired webviewId 2
(node:13235) UnhandledPromiseRejectionWarning: TypeError: Object has been destroyed
    at WebContents.send (node:electron/js2c/browser_init:2:79151)
    at IpcMainImpl.<anonymous> (/Users/kingoros/Speechify/scraping-site/GPT-4V-Act/main.js:202:15)
(node:13235) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
```

**Comment by ddupont808** [comment]
this error is from the legacy puppeteer "api". latest push w/ vision api fixes it
